/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  type Handlers = {
    'UploadPaper': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ServeStatic': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ServeCss': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'RecommendRelatedPapers': EventHandler<never, never>
    'QueryPaper': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'QueryConcepts': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GenerateSummaryWithGemini': EventHandler<never, never>
    'GenerateSummary': EventHandler<never, never>
    'GenerateMarkdownReport': EventHandler<never, never>
    'GenerateCodeExamples': EventHandler<never, never>
    'ExtractText': EventHandler<never, never>
    'ExtractEnhancedConcepts': EventHandler<never, never>
    'ExtractConceptsWithGemini': EventHandler<never, never>
    'ExtractConcepts': EventHandler<never, never>
    'EvaluateResearchImpact': EventHandler<never, never>
    'BuildKnowledgeGraph': EventHandler<never, never>
    'BuildEnhancedKnowledgeGraph': EventHandler<never, never>
    'AnalyzeResults': EventHandler<never, never>
    'AnalyzeResearchGaps': EventHandler<never, never>
    'AnalyzeRelatedLiterature': EventHandler<never, never>
    'AnalyzePaperWithGemini': EventHandler<never, never>
    'AnalyzePaper': EventHandler<never, never>
    'AnalyzeMethodology': EventHandler<never, never>
    'AnalyzeImplementationDetails': EventHandler<never, never>
    'AnalyzeCoreConcepts': EventHandler<never, never>
    'AnalyzeBenchmarks': EventHandler<never, never>
  }
}